# Generated by Django 3.2.4 on 2021-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='additional_features',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='television',
            name='picture_engine',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='television',
            name='power_consumption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='television',
            name='processor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='television',
            name='speaker_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='television',
            name='supported_app_others',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='television',
            name='supported_devices_for_casting',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='television',
            name='supported_mobile_operating_system',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='television',
            name='supported_video_formats',
            field=models.CharField(max_length=100),
        ),
    ]
