# Generated by Django 3.2.4 on 2021-10-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211002_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air_Conditioner',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.product')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('capacity_in_tons', models.CharField(max_length=50)),
                ('star_rating', models.CharField(max_length=50)),
                ('bee_rating_year', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('cooling_capacity', models.CharField(max_length=50)),
                ('compressor', models.CharField(max_length=50)),
                ('dehumidification', models.CharField(max_length=50)),
                ('remote_control', models.CharField(max_length=50)),
                ('operating_modes', models.CharField(max_length=50)),
                ('condenser_coil', models.CharField(max_length=50)),
                ('indoor_unit_whd', models.CharField(max_length=50)),
                ('indoor_unit_weight', models.CharField(max_length=50)),
                ('outdoor_unit_whd', models.CharField(max_length=50)),
                ('outdoor_unit_weight', models.CharField(max_length=50)),
                ('cooling_coverage_area', models.CharField(max_length=50)),
                ('iseer', models.CharField(max_length=50)),
                ('anti_bacteria_filter', models.CharField(max_length=50)),
                ('dust_filter', models.CharField(max_length=50)),
                ('auto_restart', models.CharField(max_length=50)),
                ('power_requirement', models.CharField(max_length=50)),
                ('power_consumption', models.CharField(max_length=50)),
                ('installation_details', models.TextField(max_length=20000)),
                ('technician_visit_details', models.TextField(max_length=10000)),
                ('uninstallation_details', models.TextField(max_length=10000)),
                ('warranty_summary', models.CharField(max_length=500)),
                ('covered_in_warranty', models.TextField(max_length=10000)),
                ('not_covered_in_warranty', models.TextField(max_length=10000)),
                ('warranty_service_type', models.CharField(max_length=50)),
            ],
            bases=('Home.product',),
        ),
    ]
