# Generated by Django 3.2.4 on 2021-10-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_air_conditioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing_Machine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.product')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('function_type', models.CharField(max_length=50)),
                ('energy_rating', models.CharField(max_length=50)),
                ('washing_capacity', models.CharField(max_length=50)),
                ('washing_method', models.CharField(max_length=50)),
                ('maximum_spin_speed', models.CharField(max_length=50)),
                ('in_built_heater', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('dryer_type', models.CharField(max_length=50)),
                ('water_level_selector', models.CharField(max_length=50)),
                ('installation_demo', models.TextField(max_length=5000)),
                ('warranty_summary', models.TextField(max_length=5000)),
                ('covered_in_warranty', models.TextField(max_length=10000)),
                ('not_covered_in_warranty', models.TextField(max_length=20000)),
                ('warranty_service_type', models.CharField(max_length=50)),
                ('fuzzy_logic', models.CharField(max_length=50)),
                ('hot_wash', models.CharField(max_length=50)),
                ('pre_wash_soak', models.CharField(max_length=50)),
                ('quick_wash', models.CharField(max_length=50)),
                ('spin_only', models.CharField(max_length=50)),
                ('spin_rinse', models.CharField(max_length=50)),
                ('tub_material', models.CharField(max_length=50)),
                ('wheel_support', models.CharField(max_length=50)),
                ('digital_display', models.CharField(max_length=50)),
                ('lint_filter', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
            bases=('Home.product',),
        ),
        migrations.RemoveField(
            model_name='television',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='television',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='television',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='television',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='television',
            name='img5',
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='', upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='', upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='', upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='', upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(default='', upload_to='pic'),
            preserve_default=False,
        ),
    ]
