# Generated by Django 3.2.4 on 2021-10-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211002_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.product')),
                ('type', models.CharField(max_length=50)),
                ('refrigerator_type', models.CharField(max_length=50)),
                ('defrosting_type', models.CharField(max_length=50)),
                ('compressor_type', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('number_of_doors', models.CharField(max_length=50)),
                ('star_rating', models.CharField(max_length=50)),
                ('coolpad', models.CharField(max_length=50)),
                ('toughened_glass', models.CharField(max_length=50)),
                ('built_in_stabilizer', models.CharField(max_length=50)),
                ('air_flow_type', models.CharField(max_length=50)),
                ('temperature_control', models.CharField(max_length=50)),
                ('express_freezing', models.CharField(max_length=50)),
                ('moisture_control', models.CharField(max_length=50)),
                ('convertible_refrigerator', models.CharField(max_length=50)),
                ('other_performance_features', models.CharField(max_length=50)),
                ('body_material', models.CharField(max_length=50)),
                ('shelf_material', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=50)),
                ('door_finish', models.CharField(max_length=50)),
                ('interior_finish', models.CharField(max_length=50)),
                ('clock', models.CharField(max_length=50)),
                ('door_lock', models.CharField(max_length=50)),
                ('gasket_type', models.CharField(max_length=50)),
                ('removable_gasket', models.CharField(max_length=50)),
                ('door_alarm', models.CharField(max_length=50)),
                ('deodorizer', models.CharField(max_length=50)),
                ('water_dispenser', models.CharField(max_length=50)),
                ('removable_rack', models.CharField(max_length=50)),
                ('flexible_rack', models.CharField(max_length=50)),
                ('power_requirement', models.CharField(max_length=50)),
                ('bee_rating_year', models.CharField(max_length=50)),
                ('stabilizer_required', models.CharField(max_length=50)),
                ('gross_refrigerator_capacity', models.CharField(max_length=50)),
                ('number_of_refrigerator_shelves', models.CharField(max_length=50)),
                ('refrigerator_interior_light', models.CharField(max_length=50)),
                ('egg_tray', models.CharField(max_length=50)),
                ('number_of_refrigerator_drawers', models.CharField(max_length=50)),
                ('number_of_refrigerator_bottle_racks', models.CharField(max_length=50)),
                ('gross_freezer_capacity', models.CharField(max_length=50)),
                ('number_of_freezer_door_bins', models.CharField(max_length=50)),
                ('freezer_interior_light', models.CharField(max_length=50)),
                ('ice_cube_tray_type', models.CharField(max_length=50)),
                ('launch_year', models.CharField(max_length=50)),
                ('net_total_capacity', models.CharField(max_length=50)),
                ('child_lock', models.CharField(max_length=50)),
                ('wheel_support', models.CharField(max_length=50)),
                ('cooling_refrigerant', models.CharField(max_length=50)),
                ('technology_used', models.CharField(max_length=50)),
                ('net_height', models.CharField(max_length=50)),
                ('net_depth', models.CharField(max_length=50)),
                ('net_width', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('installation_demo', models.TextField(max_length=5000)),
                ('warranty_summary', models.TextField(max_length=5000)),
                ('covered_in_warranty', models.TextField(max_length=10000)),
                ('not_covered_in_warranty', models.TextField(max_length=20000)),
                ('warranty_service_type', models.CharField(max_length=50)),
            ],
            bases=('Home.product',),
        ),
    ]
