# Generated by Django 3.2.4 on 2021-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='included_software',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='usb_port',
            field=models.CharField(max_length=500),
        ),
    ]
