# Generated by Django 3.2.4 on 2021-10-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_fashion_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(),
        ),
    ]
