# Generated by Django 3.2.4 on 2021-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='title_desc',
            field=models.CharField(default='NA', max_length=150),
            preserve_default=False,
        ),
    ]
